language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true


install:
  - composer install --no-interaction


script:
 - mkdir -p build/logs
 - php vendor/bin/phpunit


after_script:
 - php vendor/bin/coveralls -v
