language: php

php:
  - 5.6
  - 7.0
  - hhvm


matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true


install:
  - composer install --no-interaction


script:
 - mkdir -p build/logs
 - phpunit


after_script:
 - php vendor/bin/coveralls -v
